from _typeshed import Incomplete
from attrdict.mixins import MutableAttr

class AttrDefault(MutableAttr):
    def __init__(self, default_factory: Incomplete | None = ..., items: Incomplete | None = ..., sequence_type=..., pass_key: bool = ...) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __missing__(self, key): ...
