from _typeshed import Incomplete
from attrdict.mixins import MutableAttr

class AttrMap(MutableAttr):
    def __init__(self, items: Incomplete | None = ..., sequence_type=...) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
