"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import sys

import py2app
import sys
from distutils.core import setup
from os import getcwd
from setuptools import setup
from pathlib import Path

DATA_FILES = []
OPTIONS = dict(
    # 'iconfile': 'icon.icns',
    plist={
        'CFBundleShortVersionString': '0.5.0',
    },
    bdist_base=str(Path(getcwd())) + '/build',
    dist_dir=str(Path(getcwd())) + '/dist')
mainscript = 'imgui_desktop_app.py'

if sys.platform == 'darwin':
    extra_options = dict(
        setup_requires=['py2app'],
        app=[mainscript],
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
    )
elif sys.platform == 'win32':
    extra_options = dict(
        setup_requires=['py2exe'],
        app=[mainscript],
    )
else:
    extra_options = dict(
        # Normally unix-like platforms will use "setup.py install"
        # and install the main script as such
        scripts=[mainscript], )

setup(name="Spectograph_Viewer_PY2APP", **extra_options)
