from . import DecodeError as DecodeError
from _typeshed import Incomplete
from collections.abc import Generator

class UnsupportedError(DecodeError): ...

class MadAudioFile:
    fp: Incomplete
    mf: Incomplete
    def __init__(self, filename) -> None: ...
    def close(self) -> None: ...
    def read_blocks(self, block_size: int = ...) -> Generator[Incomplete, None, None]: ...
    @property
    def samplerate(self): ...
    @property
    def duration(self): ...
    @property
    def channels(self): ...
    def __del__(self) -> None: ...
    def __iter__(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
